koe/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.urls import path

from koe import views
from koe.request_handlers import tensorviz
from root import urls as root_urls


urlpatterns = [] + root_urls.urlpatterns


def handler500(request):
    """
    500 error handler which shows a dialog for user's feedback
    Ref: https://docs.sentry.io/clients/python/integrations/django/#message-references
    """
    return HttpResponseServerError(render(request, "500.html"))


page_names = [
    "syllables",
    "songs",
    "sequence-mining",
    "exemplars",
    "view-ordination",
    "syntax",
    "dashboard",
    "help",
]

for page_name in page_names:
    urlpatterns.append(
        path(
            "{}/".format(page_name),
            login_required(views.get_view(page_name)),
            name=page_name,
        ),
    )

urlpatterns += [
    url(r"^admin/", admin.site.urls),
    url(
        r"^segmentation/(?P<file_id>[0-9]+)/$",
        login_required(views.SegmentationView.as_view()),
        name="segmentation",
    ),
    url(
        r"^song-partition/$",
        login_required(views.SongPartitionView.as_view()),
        name="song-partition",
    ),
    url(
        r"^extraction/feature/$",
        login_required(views.FeatureExtrationView.as_view()),
        name="feature-extraction",
    ),
    url(
        r"^extraction/ordination/$",
        login_required(views.OrdinationExtrationView.as_view()),
        name="ordination-extraction",
    ),
    url(
        r"^extraction/similarity/$",
        login_required(views.SimilarityExtrationView.as_view()),
        name="similarity-extraction",
    ),
    url(
        r"^tsne/(?P<tensor_name>[0-9a-z]{32})/$",
        views.TensorvizView.as_view(),
        name="tsne",
    ),
    url(
        r"^tsne/(?P<tensor_name>[0-9a-z]{32})/meta/$",
        tensorviz.get_metadata,
        name="tsne-meta",
    ),
    path(
        "ordination/meta/<int:ord_id>/<str:viewas>/",
        login_required(tensorviz.get_ordination_metadata),
        name="ordination-meta",
    ),
    url(r"^contact-us/$", views.ContactUsView.as_view(), name="contact-us"),
    url(r"^$", views.get_home_page, name="home_page"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koe/forms.py
from django import forms
from django.conf import settings

from koe.models import Aggregation, Feature
from root.forms import ErrorMixin


cached = {}


class SongPartitionForm(ErrorMixin, forms.Form):
    track_id = forms.CharField(required=False, widget=forms.HiddenInput())

    name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={"placeholder": "Track's name"}))

    date = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS,
        required=True,
        widget=forms.DateInput(attrs={"placeholder": "YYYY-MM-DD"}),
    )


class FeatureExtrationForm(ErrorMixin, forms.Form):
    # Must do this instead of an empty Select field - because it enforces value range checking
    # and the range of an empty field is none
    data_matrix = forms.CharField(widget=forms.Select, required=False)

    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={"placeholder": "Give it a name that is easy to remember"}),
    )

    features = forms.ModelMultipleChoiceField(
        to_field_name="id",
        queryset=Feature.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        error_messages={"required": "At least one feature must be chosen"},
    )

    aggregations = forms.ModelMultipleChoiceField(
        to_field_name="id",
        queryset=Aggregation.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        error_messages={"required": "At least one aggregation method must be chosen"},
    )

    def __init__(self, *args, **kwargs):
        super(FeatureExtrationForm, self).__init__(*args, **kwargs)
        if "feature_choices" in cached:
            feature_choices = cached["feature_choices"]
        else:
            from koe.features.feature_extract import features

            feature_choices = Feature.objects.filter(id__in=[x.id for x in features])
            cached["feature_choices"] = feature_choices
        self.fields["features"].queryset = feature_choices

        if "aggregation_choices" in cached:
            aggregation_choices = cached["aggregation_choices"]
        else:
            aggregation_choices = Aggregation.objects.filter(enabled=True)
            cached["aggregation_choices"] = aggregation_choices
        self.fields["aggregations"].queryset = aggregation_choices


class OrdinationExtractionForm(ErrorMixin, forms.Form):
    data_matrix = forms.CharField(widget=forms.Select, required=True)

    ordination = forms.CharField(widget=forms.Select, required=False)

    method = forms.ChoiceField(
        required=True,
        choices=(
            ("pca", "Principal Component Analysis"),
            ("ica", "Independent Component Analysis"),
            ("tsne", "t-SNE (with PCA preprocessing)"),
        ),
    )

    ndims = forms.IntegerField(
        required=True,
        min_value=2,
        max_value=3,
        widget=forms.NumberInput(attrs={"value": 2}),
    )

    params = forms.CharField(required=False)


class SimilarityExtractionForm(ErrorMixin, forms.Form):
    data_matrix = forms.CharField(widget=forms.Select, required=False)
    ordination = forms.CharField(widget=forms.Select, required=False)


class ContactUsForm(ErrorMixin, forms.Form):
    name = forms.CharField(
        required=True,
        max_length=100,
        error_messages={"required": "Please let us know your name"},
        widget=forms.TextInput(attrs={"placeholder": "Your name"}),
    )

    email = forms.EmailField(
        required=True,
        max_length=100,
        error_messages={"required": "This field is required"},
        widget=forms.TextInput(attrs={"placeholder": "Your email"}),
    )

    message = forms.CharField(
        required=True,
        min_length=50,
        max_length=1000000,
        error_messages={"required": "Please leave a message"},
        widget=forms.Textarea(attrs={"cols": 80, "rows": 10, "minlength": 50, "maxlength": 1000000}),
    )

templates/partials/contact-us-form.html
{% load widget_tweaks %}

<div class="form-group">
    <label for="{{ form.name.id_for_label }}" class="control-label">Your name</label>
    <div class="input-group">
        {{ form.name|add_error_class:"has-error"|add_class:"form-control" }}
    </div>
    {{ form.name.errors }}
</div>

<div class="form-group">
    <label for="{{ form.email.id_for_label }}" class="control-label">Email</label>
    <div class="input-group">
        {{ form.email|add_error_class:"has-error"|add_class:"form-control" }}
    </div>
    {{ form.email.errors }}
</div>

<div class="form-group">
    <label for="{{ form.password.id_for_label }}" class="control-label">Message</label>
    <div class="input-group">
        {{ form.message|add_error_class:"has-error"|add_class:"form-control" }}
    </div>
    {{ form.message.errors }}
</div>

templates/partials/download-csv-btns.html
<div class="btn-group dropup" role="group">
    <button type="button" class="btn btn-black dropdown-toggle" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
        Export
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a class="download-xls" data-download-type="all">Entire table</a></li>
        <li><a class="download-xls" data-download-type="visible-rows-only">Visible rows only</a>
        </li>
    </ul>
</div>

templates/partials/download-songs-modal.html
<div class="modal fade in" id="download-songs-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
     data-backdrop="static" aria-hidden="true" style="display: none;"
     {% if current_database.is_real %}database="{{ current_database.id }}"{% endif %}>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Downloading songs</h3>
            </div>
            <div class="modal-body">
                <div id="instruction" class="bs-callout bs-callout-primary" style="">
                    <h4>Competed <span id="current-file-no"></span>/<span id="total-files-count"></span></h4>
                    <span id="current-file-name"></span>
                </div>

                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0"
                     aria-valuemax="100" aria-valuenow="0">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/feature-selection-form.html
{% load staticfiles %}
{% load widget_tweaks %}

<div class="form-group selectize">
    <label for="{{ form.data_matrix.id_for_label }}" class="control-label">Existing data matrices</label>
    <select name="data_matrix" class="form-control {% if form.data_matrix.errors %}has-error{% endif %}"
            id="id_data_matrix" tabindex="-1">
        <option value="">---------</option>
        {% for dm in completed_dms %}
            <option value="{{ dm.id }}">
                {{ dm }} | Completed
            </option>
        {% endfor %}
        {% for dm in incomplete_dms %}
            <option value="{{ dm.id }}">
                {{ dm }} | Not completed yet
            </option>
        {% endfor %}
    </select>
    {{ form.data_matrix.errors }}
</div>


<div class="form-group">
    <label for="{{ form.features.id_for_label }}" class="control-label">Features</label>
    <div class="row no-margin" id="{{ form.features.auto_id }}">
        {% for choice in form.features %}
            <label class=" col-xs-6 col-sm-4 col-md-3 col-lg-2">
                {{ choice }}
            </label>
        {% endfor %}
    </div>
    {{ form.features.errors }}
</div>

<div class="form-group">
    <label for="{{ form.aggregations.id_for_label }}" class="control-label">Aggregation methods</label>
    <div class="row no-margin" id="{{ form.aggregations.auto_id }}">
        {% for choice in form.aggregations %}
            <label class=" col-xs-6 col-sm-4 col-md-3 col-lg-2">
                {{ choice }}
            </label>
        {% endfor %}
    </div>
    {{ form.aggregations.errors }}
</div>

<div class="form-group">
    <label for="{{ form.name.id_for_label }}" class="control-label">Name</label>
    {{ form.name|add_error_class:"has-error"|add_class:"form-control" }}
    {{ form.name.errors }}
</div>

templates/partials/go-to-songs-modal.html
{% load static %}

<div class="modal fade in" id="go-to-songs-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
     data-backdrop="static" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Please navigate to "View all songs" and click on the filename of the song you want to segment.</h3>
            </div>
            <div class="modal-body">
                <h5>
                    Like this:
                </h5>

                <img src="{% static 'images/go-to-song-segmentation.png' %}">
            </div>

            <div class="modal-footer">
                <div class="btn-group btn-group-justified" role="group" aria-label="group button">
                    <div class="btn-group" role="group">
                        <a class="btn btn-primary appendable" href="{% url 'songs' %}">
                            Take me there
                        </a>
                    </div>
                    <div class="btn-group" role="group">
                        <button class="btn btn-primary" data-dismiss="modal" role="button">Never mind</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

templates/partials/modal.html
{% load cache %}
{% cache None modal order yes no%}
<div class="modal fade in" id="dialog-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
     data-backdrop="static" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" style="">
        <div class="modal-content" style="">
            <div class="modal-header">
                <h3 class="modal-title"></h3>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <div class="btn-group btn-group-justified" role="group" aria-label="group button">
                    {% if order == 'yes-no' %}
                        <div class="btn-group" role="group">
                            <button type="button" id="dialog-modal-yes-button"
                                    class="btn btn-primary btn-hover-green"
                                    role="button">
                                {{ yes }}
                            </button>
                        </div>
                        <div class="btn-group" role="group">
                            <button type="button" id="dialog-modal-no-button"
                                    class="btn btn-primary" data-dismiss="modal" role="button">
                                {{ no }}
                            </button>
                        </div>
                    {% else %}
                        <div class="btn-group" role="group">
                            <button type="button" id="dialog-modal-no-button" class="btn btn-primary"
                                    data-dismiss="modal" role="button">
                                {{ no }}
                            </button>
                        </div>
                        <div class="btn-group" role="group">
                            <button type="button" id="dialog-modal-yes-button"
                                    class="btn btn-primary btn-hover-green"
                                    role="button">
                                {{ yes }}
                            </button>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endcache %}

templates/partials/navbar-item.html
{% if current_page == page.url %}
    <li class="active"><a href="#">{{ page.text }}</a></li>
{% else %}
    <li><a href="{{ page.url }}">{{ page.text }}</a></li>
{% endif %}

templates/partials/navbar-menu.html
{% if page.is_single %}
    {% include "partials/navbar-item.html" with page=page current_page=current_page %}
{% else %}
    <li class="dropdown {% if current_page == page.url %}active{% endif %}">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ page.text }}<span class="caret"></span></a>
        <ul class="dropdown-menu">
            {% for subpage in page.subpages %}
                {% include "partials/navbar-item.html" with page=subpage current_page=current_subpage%}
            {% endfor %}
        </ul>
    </li>
{% endif %}

templates/partials/page-controller-settings-btn.html
<span class="input-group-addon right dropdown">
    <button class="btn btn-primary btn-xs dropdown-toggle" type="button"
            id="features-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <span rel="tooltip" data-toggle="tooltip" data-trigger="hover" data-animation="false"
              data-placement="top" title="" class="fa fa-cogs">
        </span>&nbsp
        <span class="caret"></span>
    </button>

    <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu">
        <li class="dropdown-submenu">
            <a id="database-select-combo" data-toggle="dropdown" database="{{ current_database.id }}"
               cls="{{ current_database_owner_class }}" current-attr="current-database">Database</a>
            <ul class="dropdown-menu">
                {% if databases %}
                {% for database in databases %}
                <li class="{% if current_database.id == database.id %}active{% else %}not-active{% endif %}">
                    <a href="#" class="select-database" database="{{ database.id }}">
                        {{ database.name }}
                    </a>
                </li>
                {% endfor %}
                <li class="divider"></li>
                {% endif %}
                {% if inaccessible_databases %}
                <li class="dropdown-submenu">
                    <a href="#">Request access</a>
                    <ul class="dropdown-menu">
                        {% for database in inaccessible_databases %}
                            <li>
                                <a href="#" class="request-database" database="{{ database.id }}">
                                    {{ database.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                    <li class="divider"></li>
                {% endif %}

                {% if pending_requests %}
                <li class="dropdown-submenu">
                    <a href="#">Approve Request</a>
                    <ul class="dropdown-menu">
                        {% for request in pending_requests %}
                            <li>
                                <a href="#" class="approve-request" request="{{ request.id }}">
                                    <strong>{{ request.user.username }}</strong> requested permission to
                                    <strong>{{ request.get_permission_display | lower }} </strong>
                                    database <strong>{{ request.database.name }}</strong>. Click to approve.
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="divider"></li>
                {% endif %}

                <li><a href="#" id="create-database-btn">Create new database</a></li>
            </ul>
        </li>
        {% if similarities %}
            <li class="dropdown-submenu">
            <a id="similarity-sort-combo" data-toggle="dropdown" similarity="{{ current_similarity.id }}"
               cls="{{ current_similarity_owner_class }}" current-attr="current-similarity"
               owner-id="{{ current_database_owner_id }}">Sort algorithm</a>
            <ul class="dropdown-menu">
                {% for similarity in similarities %}
                    <li class="{% if current_similarity == similarity %}active{% else %}not-active{% endif %}">
                        <a class="select-similarity" href="#" similarity="{{ similarity.id }}">
                            {{ similarity.algorithm }}
                        </a>
                    </li>
                {% endfor %}
            </ul>

        </li>
        {% endif %}
    </ul>
</span>

templates/partials/preset_dropdown_list_options.html
{% if tensors %}
    <option value="">---------</option>
    {% for tensor in tensors %}
        <option value="{{ tensor.id }}">
            Created by {{ tensor.creator.username }} at {{ tensor.created }} |
            Annotator: {{ tensor.annotator.username }} |
            {% if tensor.dimreduce == 'none' %}
                No reduction
            {% else %}
                Reuduction: {{ tensor.dimreduce }}, {{ tensor.ndims }} dims
            {% endif %}
        </option>
    {% endfor %}
{% else %}
    <option value="">No data matrix available - contact admin</option>
{% endif %}

templates/partials/similarity-extraction-tasks.html
{% load staticfiles %}
{% load widget_tweaks %}

{% if task %}
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        <strong>Success!</strong>
        Task #{{ task.id }} has been submitted and scheduled to run. You will get an email notification when it
        finishes. You do not need to leave this tab open.
    </div>
{% endif %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <div id="menu-opener">
            <i class="fa fa-white fa-bars left siderbar-toggler" aria-hidden="true"></i>
        </div>
        <strong>Similarity extraction queue</strong>
    </div>
    <div class="panel-body">
        <p>Following are pending similarity calculation tasks submitted by all users for all databases and collections.</p>
    </div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Task</th>
            <th>Username</th>
            <th>Database</th>
            <th>Source type</th>
            <th>Source name</th>
            <th>Created</th>
            <th>Started</th>
            <th>Progress</th>
        </tr>
        </thead>
        <tbody>
        {% for sim, subtasks in all_incomplete_sims2tasks %}
            <tr>
                <th scope="row">{{ sim.task.id }}</th>
                <td>{{ sim.task.user.username }}</td>
                {% if sim.dm %}
                    {% if sim.dm.database %}
                        <td>{{ sim.dm.database.name }}</td>
                    {% else %}
                        <td>{{ sim.dm.tmpdb.name }}</td>
                    {% endif %}
                    <td>DataMatrix</td>
                    <td>{{ sim.dm.name }}</td>
                {% else %}
                    {% if sim.ord.dm.database %}
                        <td>{{ sim.ord.dm.database.name }}</td>
                    {% else %}
                        <td>{{ sim.ord.dm.tmpdb.name }}</td>
                    {% endif %}
                    <td>Ordination</td>
                    <td>{{ sim.ord.name }}</td>
                {% endif %}
                <td>{{ sim.task.created }}</td>
                <td>{{ sim.task.started }}</td>
                <td>
                    <div class="progress">
                        <span class="progress-value">{{ sim.task.pc_complete | floatformat }}% {{ sim.task.get_stage_display }}</span>
                        <div class="progress-bar progress-bar-primary progress-bar-striped" role="progressbar"
                             aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
                             style="width: {{ sim.task.pc_complete | floatformat }}%">
                        </div>
                    </div>
                </td>
            </tr>
            {% for subtask in subtasks %}
                <tr class="subtask">
                    <td colspan="5">Subtask #{{ subtask.id }}</td>
                    <td>{{ subtask.created }}</td>
                    <td>{{ subtask.started }}</td>
                    <td>
                        <div class="progress">
                            <span class="progress-value">{{ subtask.pc_complete | floatformat }}% {{ subtask.get_stage_display }}</span>
                            <div class="progress-bar progress-bar-primary progress-bar-striped" role="progressbar"
                                 aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
                                 style="width: {{ subtask.pc_complete | floatformat }}%">
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
</div>

templates/partials/track-info-form.html
{% load widget_tweaks %}

<input type="hidden" name="track_id" {% if track_id %} value="{{ track_id }}" {% endif %} id="id_track_id"
       valid="{% if valid %}true{% else %}false{% endif %}">

<div class="input-group input-group-sm">
    <span class="input-group-addon">Track name</span>
    {{ form.name|add_error_class:"has-error"|add_class:"form-control" }}
    {{ form.name.errors }}
</div>

<div class="input-group input-group-sm">
    <span class="input-group-addon">Record date</span>
    {{ form.date|add_error_class:"has-error"|add_class:"form-control" }}
    {{ form.date.errors }}
</div>

templates/partials/upload-csv-modal.html
<form id="csv-upload-form" method="post" enctype="multipart/form-data" style="display: none">
    <input type="file" name="file" accept="text/csv">
    <input class="database-value" name="database" type="text" value="{{ current_database.id }}">
    <input type="submit">
</form>
<div class="modal fade in" id="upload-csv-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
     data-backdrop="static" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" style="">
        <div class="modal-content" style="">
            <div class="modal-header">
                <h3 class="modal-title">Upload data to table</h3>
            </div>
            <div class="modal-body">
                <div>
                    <h4>Upload a CSV file to change data in this table.</h4>
                    <ul>
                        <li>Each row in the CSV will be matched against rows
                    in the current table using the value in column <strong><span class="import-key"></span></strong>.</li>
                        <li>Only the following columns are accepted, unmatched columns are ignored.</li>
                        <li>Rows that have <strong><span class="import-key"></span></strong> not found in the table is also ignored</li>
                        <li>Rows that have the same values as current in the database will also be ignored</li>
                        <li>The best approach is to export this table as CSV, make changes and then upload</li>
                        <li>Mind you, most columns are exportable - only editable columns are importable.</li>
                        <li>IMPORTANT: Date field must be exported in the YYYY-MM-DD format</li>
                    </ul>

                    <div id="importable-table-wrapper">
                        <h4>These are the columns that can be imported if present in your CSV</h4>
                        <ul>
                            <li>Importable data from you CSV file will be appended to the table below after upload for
                                your review.
                            </li>
                            <li>If everything looks fine, click "Process" after upload your CSV</li>
                        </ul>
                        <div class="table-wrapper">
                            <table class="table table-bordered table-condensed table-striped table-hover">
                            </table>
                        </div>
                    </div>

                    <div id="unimportable-table-wrapper">
                        <h4>These are columns with invalid values</h4>
                        <ul>
                            <li>Please fix these problems and try again</li>
                        </ul>
                        <div class="table-wrapper">
                            <table class="table table-bordered table-condensed table-striped table-hover">
                            </table>
                        </div>
                    </div>

                    <div class="alert alert-danger">
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <div class="message"></div>
                    </div>
                    <div class="alert alert-warning">
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <div class="message"></div>
                    </div>
                    <div class="alert alert-success">
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <div class="message"></div>
                    </div>
                </div>

                <br>
            </div>

            <div class="modal-footer">
                <form id="file-upload-form" method="post" enctype="multipart/form-data" style="display: none">
                    <input type="file" name="file" accept="text/csv">
                    <input class="database-value" name="database" type="text" value="{{ current_database.id }}">
                    <input type="submit">
                </form>

                <div class="btn-group btn-group-justified" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                        <button id="upload-csv-btn" type="button" class="btn btn-primary">Upload</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button disabled id="process-csv-btn" type="button" class="btn btn-primary">Process</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button id="cancel-btn" data-dismiss="modal" role="button" type="button" class="btn btn-primary">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>